#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define MPI 3.141592653589793

#define double_eps 1E-2

#define DEBUG_NO_MOTORS
//#define DEBUG_NO_GYROSCOPE
//#define DEBUG_NO_ACCELEROMETER
#define DEBUG_SERIAL
#define DEBUG_SERIAL_HUMAN

#endif
